[phases.setup]
aptPkgs = ["ffmpeg", "libopus0", "libsodium23", "python3-dev"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python main.py"
